# ==============================================================================
# 3 - Bootstrapping
# ==============================================================================

#-------------------------------------------------------------------------------
# i)
#-------------------------------------------------------------------------------

# A bootstrapped dataset is generated by choosing a random set of values and
# creating a new dataset from the previously chosen dataset by selecting random 
# values (including duplicate values). 
# Now, bootstrapping is the process of preparing a bootstrapped dataset,
# calculating any statistic and then keeping track of those calculations.


#-------------------------------------------------------------------------------
# ii)
#-------------------------------------------------------------------------------
# Generate a sample of exponential data with n = 100 and λ = 1.
# Bootstrap this data 1000 times, calculating the the median for the
# sample in each bootstrapped sample. The 0.025 and 0.975 quantiles of
# the distribution of bootstrapped medians provides a confidence interval
# for the median.

seednumber <- 25189506+25203533
set.seed(seednumber)

exp_data <- rexp(100, rate = 1)

medians_list <- numeric(1000)


for (i in 1:1000) {
  sample_i <- sample(exp_data, size = 100, replace = TRUE)
  medians_list[i] <- median(sample_i)
}

head(medians_list)
mean(medians_list)
quantile(medians_list, c(0.025, 0.975))


#-------------------------------------------------------------------------------
# iii)
#-------------------------------------------------------------------------------
# Repeat part (ii) here 1000 times to evaluate the performance of the confidence
# interval. Note: here you need to work out the value of the true median first, 
# i.e., the value of m such that Pr(X > m) = 0.5 (and show your workings). Also,
# do not get mixed up between the 1000 bootstraps carried out in each of the 1000
# simulation replicates, i.e., 1000 bootstraps are required to produce a confidence
# interval (per part (ii) of this question), but then this procedure is repeated
# 1000 times to assess the performance of the bootstrapped confidence intervals.

lambda_true <- 1
median_true <- log(2) / lambda_true

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(100, rate = lambda_true)
  
  medians_list <- numeric(1000)
  
  for (i in 1:1000) {
    sample_i <- sample(exp_data, size = 100, replace = TRUE)
    medians_list[i] <- median(sample_i)
  }
  
  median <- mean(medians_list)
  median_list <- append(median_list, median)
  
  ci_lower <- quantile(unlist(medians_list), probs = 0.025)
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- quantile(unlist(medians_list), probs = 0.975)
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  Median = unlist(median_list),
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)


#-------------------------------------------------------------------------------
# iv)
#-------------------------------------------------------------------------------
# By hand, derive the an approximate confidence interval (Wald-type)
# for λ (showing workings) and, hence, for the median m. Evaluate the
# performance of this confidence interval.

lambda_true <- 1
median_true <- log(2) / lambda_true

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(100, rate = lambda_true)
  
  lambda_hat <- 1/mean(exp_data)
  
  ci_lower <- log(2)/(lambda_hat + (1.96*lambda_hat/100**0.5))
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- log(2)/(lambda_hat - (1.96*lambda_hat/100**0.5))
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)


#-------------------------------------------------------------------------------
# v)
#-------------------------------------------------------------------------------
# Repeat parts (iii) and (iv) for n = 10 and n = 50. Comment on the
# results.

# ------------------------------------------------------------------------------
# For n = 10
lambda_true <- 1
median_true <- log(2) / lambda_true

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(10, rate = 1)
  
  medians_list <- numeric(1000)
  
  for (i in 1:1000) {
    sample_i <- sample(exp_data, size = 10, replace = TRUE)
    medians_list[i] <- median(sample_i)
  }
  
  median <- mean(medians_list)
  median_list <- append(median_list, median)
  
  ci_lower <- quantile(unlist(medians_list), probs = 0.025)
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- quantile(unlist(medians_list), probs = 0.975)
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  Median = unlist(median_list),
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)

# Wald CI
lambda_true <- 1
median_true <- log(2) / lambda_true

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(10, rate = lambda_true)
  
  lambda_hat <- 1/mean(exp_data)
  
  ci_lower <- log(2)/(lambda_hat + (1.96*lambda_hat/10**0.5))
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- log(2)/(lambda_hat - (1.96*lambda_hat/10**0.5))
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)

# ------------------------------------------------------------------------------
# For n= 50
lambda_true = 0.6931

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(50, rate = 1)
  
  medians_list <- numeric(1000)
  
  for (i in 1:1000) {
    sample_i <- sample(exp_data, size = 50, replace = TRUE)
    medians_list[i] <- median(sample_i)
  }
  
  median <- mean(medians_list)
  median_list <- append(median_list, median)
  
  ci_lower <- quantile(unlist(medians_list), probs = 0.025)
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- quantile(unlist(medians_list), probs = 0.975)
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  Median = unlist(median_list),
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)

# Wald CI
lambda_true <- 1
median_true <- log(2) / lambda_true

reps <- 1000

seednumber <- 25189506+25203533
set.seed(seednumber)

median_list <- list()
performance_list <- list()
ci_lower_list <- list()
ci_upper_list <- list()

for (i in 1:reps) {
  exp_data <- rexp(50, rate = lambda_true)
  
  lambda_hat <- 1/mean(exp_data)
  
  ci_lower <- log(2)/(lambda_hat + (1.96*lambda_hat/50**0.5))
  ci_lower_list <- append(ci_lower_list, ci_lower)
  ci_upper <- log(2)/(lambda_hat - (1.96*lambda_hat/50**0.5))
  ci_upper_list <- append(ci_upper_list, ci_upper)
  
  is_median_present <- (median_true >= ci_lower) && (median_true <= ci_upper)
  performance_list <- append(performance_list, is_median_present)
}

Fit_Medians_Count <- sum(unlist(performance_list))

Performance <- Fit_Medians_Count/reps

OutputData <- list(
  CI_0.025 = unlist(ci_lower_list),
  CI_0.975 = unlist(ci_upper_list),
  Performance = unlist((performance_list))
)

df <- as.data.frame(OutputData)

